name: Bug report
description: Report a problem with app behavior, image, or docs.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please include enough detail to reproduce it.
  - type: input
    id: version
    attributes:
      label: Image tag/version
      placeholder: "main or v1.2.3"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Docker host OS, Docker version, and deployment method.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
